// Thin fetch client for the MED-UNIDAVI backend.
// - Dev: Vite proxies /api → the Express + SQLite server (live backend).
// - Production build (e.g. Vercel static deploy): the same payloads are read
//   from pre-generated static JSON snapshots in /data (no server needed).
const BASE = import.meta.env.VITE_API_URL || '';
const STATIC = import.meta.env.PROD && !import.meta.env.VITE_API_URL;

// Logical API path → static snapshot file (generated by api/src/export-static.js).
const STATIC_MAP = {
  '/dashboard': '/data/dashboard.json',
  '/tutor/panel': '/data/tutor-panel.json',
  '/coordenacao/overview': '/data/coordenacao-overview.json',
  '/students': '/data/students.json',
  '/students/joao-melo/profile': '/data/joao-melo-profile.json',
  '/competencies/dcn27': '/data/dcn27.json',
};

export async function apiGet(path) {
  const url = STATIC ? (STATIC_MAP[path] || `/data${path.replace(/\//g, '_')}.json`) : `${BASE}/api${path}`;
  const res = await fetch(url, { headers: { Accept: 'application/json' } });
  if (!res.ok) {
    const body = await res.text().catch(() => '');
    throw new Error(`GET ${path} → ${res.status} ${body.slice(0, 200)}`);
  }
  return res.json();
}

export async function apiPost(path, payload) {
  // In the static deploy there is no server to receive events — synthesize a
  // protocol locally so the UI flow (e.g. Canal FAB confirmation) still works.
  if (STATIC) return { ok: true, protocolo: `CANAL-${Date.now().toString(36).toUpperCase()}`, ...payload };
  const res = await fetch(`${BASE}/api${path}`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json', Accept: 'application/json' },
    body: JSON.stringify(payload),
  });
  if (!res.ok) throw new Error(`POST ${path} → ${res.status}`);
  return res.json();
}

// React hook: fetch once on mount, expose { data, error, loading }.
import { useState, useEffect } from 'react';
export function useApi(path, deps = []) {
  const [state, setState] = useState({ data: null, error: null, loading: true });
  useEffect(() => {
    let alive = true;
    setState(s => ({ ...s, loading: true, error: null }));
    apiGet(path)
      .then(data => { if (alive) setState({ data, error: null, loading: false }); })
      .catch(error => { if (alive) setState({ data: null, error, loading: false }); });
    return () => { alive = false; };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, deps);
  return state;
}
